"""Write ``results/part2/report.md`` from the saved ``metrics.json`` and ``run.json``.

The report is regenerated by ``make train`` together with the other Part II
results, so every number in it is the value stored in the two JSON files.
Sections for tasks that have not run yet (``run_task_a`` alone) are skipped.
"""

from __future__ import annotations

import json
from pathlib import Path

DECODERS = ('belief_matching', 'correlated_matching', 'pymatching', 'tensor_network_contraction')


def _number(value, digits=6):
    return 'not applicable' if value is None else f'{value:.{digits}f}'


def _seconds(value):
    return 'not applicable' if value is None else f'{value:.4f}'


def _result_table(metrics, weighted=False):
    rows_label = 'Test rows (physical observations)' if weighted else 'Test rows'
    lines = [f'| Model | {rows_label} | Logical-error rate | Balanced accuracy | Brier | Training s | Prediction s |',
             '| --- | ---: | ---: | ---: | ---: | ---: | ---: |']
    for name, scores in metrics.items():
        m = scores['test']
        rows = f"{m['aggregate_rows']:,}"
        if weighted:
            rows += f" ({m['physical_observations']:,})"
        lines.append(f"| {name} | {rows} | {_number(m['logical_error_rate'])} | {_number(m['balanced_accuracy'])} | "
                     f"{_number(m['brier_score'])} | {_seconds(m['training_time_seconds'])} | "
                     f"{_seconds(m['prediction_time_seconds'])} |")
    return lines


def _top_two(record):
    """Name the two largest decoder weights of each combined model, e.g. for d=3 and d=5."""
    parts = []
    for distance in (3, 5):
        weights = {k.removesuffix('_prediction'): v for k, v in
                   record['models'][f'task_b_d{distance}_logistic_regression']['coefficients'].items()
                   if k != 'detector_event_density'}
        top = sorted(weights, key=weights.get, reverse=True)[:2]
        parts.append(f"{top[0]} and {top[1]} (d={distance})")
    return ' and '.join(parts) if parts[0].split(' (')[0] != parts[1].split(' (')[0] else parts[0].split(' (')[0]


def _test(metrics, task, model):
    return metrics[task][model]['test']


def _intro(record):
    hashes = record['input_hashes']
    return ['# Part II report: AI/ML consumer of the QEC pipeline', '',
            'Generated by `make train` from `metrics.json` and `run.json`; every number below is copied from '
            'those files. Training reads only the two ML Parquet tables exported from Gold in Part I '
            f"(release `{record['data_release']}`, bundle version {record['bundle_version']}). "
            'Both table contracts are validated before training. Input hashes: '
            f"`ml_syndrome_decoder_example` {hashes['ml_syndrome_decoder_example'][:12]}..., "
            f"`ml_google_decoder_example` {hashes['ml_google_decoder_example'][:12]}... "
            f"(full values, code revision, dependency versions and seed {record['random_seed']} are in `run.json`). "
            'Model performance is not the goal; the tasks check that the prepared data can be consumed and '
            'evaluated reproducibly.']


def _inputs_section(record):
    a = record.get('report_context', {}).get('task_a', {})
    rows = record.get('split_rows', {})
    lines = ['', '## Inputs, targets and splits', '',
             '| Task | Input table and rows | Model input (order in `run.json`) | Target | Split rule |',
             '| --- | --- | --- | --- | --- |']
    if a:
        n = a['split_rows']
        lines.append(f"| A | `ml_syndrome_decoder_example`, {n['train']:,} / {n['validation']:,} / {n['test']:,} "
                     'aggregate rows (train / validation / test) | 16 syndrome values, round first then check | '
                     '`logical_error_label` | validation: fault rate 0.0005; test: 0.005; train: other five rates |')
    for distance in (3, 5):
        n = rows.get(f'task_b_d{distance}')
        if n:
            lines.append(f"| B, d={distance} | `ml_google_decoder_example`, {n['train']:,} / {n['validation']:,} / "
                         f"{n['test']:,} shots | detector-event density (`detector_event_count / detector_count`), "
                         'then the four supplied predictions | `actual_observable_flip` | per experiment: odd '
                         '`shot_index` test; `shot_index % 10 == 8` validation; other even train |')
    n = rows.get('task_c')
    if n:
        lines.append(f"| C | `ml_google_decoder_example` with `distance = 3 AND shot_index < 12500`, "
                     f"{n['train']:,} / {n['validation']:,} / {n['test']:,} shots | detector bits 0 to 199, "
                     'little-endian within each byte, padding dropped | `actual_observable_flip` | Google split '
                     'retained inside the subset |')
    if a:
        p = a['physical_observations']
        lines += ['', f"Task A rows are aggregates. `sample_weight` (the source `quantity`) gives "
                  f"{p['train']:,} / {p['validation']:,} / {p['test']:,} physical observations per split. "
                  'It is used when fitting the logistic regression and in every Task A metric; it is never a '
                  'feature and rows are never expanded.']
    return lines


def _choices_section(record):
    return ['', '## Model choices', '',
            '- **Priors (Tasks A and B).** The training-set positive rate (physically weighted in Task A) used '
            'as a constant probability. It shows what the label imbalance alone achieves.',
            '- **Logistic regression (Tasks A and B).** One weight per input plus an intercept. Task A has 16 '
            'binary inputs and Task B five, so a linear model is the smallest learned model that uses every '
            'input, accepts physical sample weights, and gives probabilities for the Brier score.',
            '- **Supplied decoders (Task B).** Their stored predictions are evaluated directly. They give no '
            'probability, so their Brier score is not applicable.',
            '- **MLP (Task C).** One hidden layer of 32 ReLU units on the 200 raw bits, Adam, at most 50 '
            'iterations, seed fixed. It is the required bounded prototype, not a tuned architecture.',
            '',
            'All settings (C = 1, threshold 0.5, MLP size and iterations) were fixed before evaluation. Fitting '
            'uses only training rows. Validation scores are saved in `metrics.json` as a check but were not used '
            'to tune anything, and test rows are used once for the tables below. Within a task and distance '
            'every model is scored on the same test examples.',
            '',
            'Timing convention: training time covers only the fit call (for a prior, computing the training '
            'rate); prediction time covers only scoring the test rows. Loading, contract validation and feature '
            'construction are excluded. The supplied decoders have no local training or prediction step, so '
            'both timings are not applicable. Run-level start and end times are in `run.json`; elapsed times '
            'vary between runs while predictions and metrics do not.']


def _task_a(metrics, record):
    a = record['report_context']['task_a']
    rate = a['weighted_positive_rate']
    prior = _test(metrics, 'task_a', 'task_a_weighted_prior')
    linear = _test(metrics, 'task_a', 'task_a_logistic_regression')
    lines = ['', '## Task A: weighted syndrome decoder', '',
             'Test set: the 0.005 fault-rate file. All metrics use physical weights.', '',
             *_result_table(metrics['task_a'], weighted=True), '',
             f"Logical errors are {rate['train']:.2%} of training observations, {rate['validation']:.2%} of "
             f"validation observations and {rate['test']:.2%} of test observations. The prior therefore always "
             'predicts "no logical error"; its error rate equals the test positive rate and its balanced accuracy '
             'is 0.5.']
    if linear['logical_error_rate'] > prior['logical_error_rate']:
        lines += ['', f"The linear model has a higher test logical-error rate than the prior "
                  f"({linear['logical_error_rate']:.6f} vs {prior['logical_error_rate']:.6f}). Its higher balanced "
                  f"accuracy ({linear['balanced_accuracy']:.6f}) shows it flags some logical errors the prior "
                  'misses, but at threshold 0.5 its false alarms outnumber those catches. Its lower Brier score '
                  f"({_number(linear['brier_score'])} vs {_number(prior['brier_score'])}) means its probabilities are "
                  'more informative than the constant. On the main metric this is a negative result.']
    else:
        lines += ['', f"The linear model has a test logical-error rate of {linear['logical_error_rate']:.6f}, "
                  f"against {prior['logical_error_rate']:.6f} for the prior."]
    by_rate = a['weighted_positive_rate_by_fault_rate']
    lines += ['', 'The split holds out whole fault rates, and the label rate depends strongly on the fault rate, '
              'which is not a model input:', '',
              '| Physical fault rate | Split | Logical-error rate (weighted) |', '| ---: | --- | ---: |',
              *[f"| {r['physical_fault_rate']:g} | {r['split']} | {r['weighted_positive_rate']:.4%} |" for r in by_rate],
              '', 'The test rate is outside most of the training range, so the model is evaluated under a shift '
              'in label frequency. This describes the supplied split; it does not show how either model would '
              'behave on hardware data.']
    return lines


def _task_b(metrics, record):
    context = record['report_context']
    lines = ['', '## Task B: supplied and combined Google decoders', '',
             'Distances three and five are fitted and evaluated separately because their detector layouts differ '
             '(200 and 600 bits). The four distance-three experiments are pooled; processor location is not an input.']
    for distance in (3, 5):
        task = f'task_b_d{distance}'
        scores = metrics[task]
        combined = scores[f'{task}_logistic_regression']['test']['logical_error_rate']
        supplied = {d: scores[f'{task}_{d}']['test']['logical_error_rate'] for d in DECODERS}
        best = min(supplied, key=supplied.get)
        c = context[task]
        lines += ['', f'### Distance {distance}', '', *_result_table(scores), '',
                  f"Against the best supplied decoder on these shots ({best}, {supplied[best]:.6f}), the combined "
                  f"model changes the logical-error rate by {combined - supplied[best]:+.6f}. On the same shots it "
                  f"is right where {best} is wrong {c['combined_right_best_wrong']:,} times and wrong where "
                  f"{best} is right {c['combined_wrong_best_right']:,} times, out of {c['test_rows']:,}."]
    lines += ['', '### Do the supplied decoders make the same mistakes?', '',
              '| Distance | Test shots | All four right | 1 wrong | 2 wrong | 3 wrong | All four wrong | '
              'Combined error rate where decoders disagree |',
              '| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |']
    for distance in (3, 5):
        c = context[f'task_b_d{distance}']
        k = c['shots_by_decoders_wrong']
        lines.append(f"| {distance} | {c['test_rows']:,} | {k['0']:,} | {k['1']:,} | {k['2']:,} | {k['3']:,} | "
                     f"{k['4']:,} | {_number(c['combined_error_rate_when_decoders_disagree'], 4)} |")
    lines += ['', 'Pairwise view (test shots):', '',
              '| Distance | First decoder | Second decoder | Both wrong | Only first wrong | Only second wrong |',
              '| --- | --- | --- | ---: | ---: | ---: |']
    for distance in ('3', '5'):
        for p in record['decoder_overlap'][distance]:
            lines.append(f"| {distance} | {p['first'].removesuffix('_prediction')} | "
                         f"{p['second'].removesuffix('_prediction')} | {p['both_wrong']:,} | "
                         f"{p['only_first_wrong']:,} | {p['only_second_wrong']:,} |")
    d3, d5 = context['task_b_d3'], context['task_b_d5']
    shared = [c['shots_by_decoders_wrong']['4'] / c['test_rows'] for c in (d3, d5)]
    lines += ['', 'The decoders overlap heavily but not completely. On '
              f"{shared[0]:.1%} (d=3) and {shared[1]:.1%} (d=5) of test shots all four are wrong; there the "
              'four prediction inputs agree on the wrong answer, so the combined model can only differ through '
              'event density. The one-sided errors are where a combination could help, but the combined model '
              'only sees which decoders vote for a flip plus one density value. It cannot tell which decoder is '
              f'right on a particular shot. Its fitted weights (in `run.json`) are largest for {_top_two(record)}, '
              'so it behaves like a weighted vote of the decoders. The small '
              'differences from the best supplied decoder, in both directions, should not be read as a reliable '
              'improvement.']
    return lines


def _task_c(metrics, record):
    m = _test(metrics, 'task_c', 'task_c_d3_mlp')
    c = record['report_context']['task_c']
    settings = record['models']['task_c_d3_mlp']
    decoders = ', '.join(f"{name.removesuffix('_prediction')} {value:.4f}"
                         for name, value in c['supplied_decoder_test_logical_error_rate'].items())
    lines = ['', '## Task C: bounded raw-detector prototype', '',
             *_result_table(metrics['task_c']), '',
             f"Reference values on the same {m['aggregate_rows']:,} test shots (not models of this task): the "
             f"training-majority baseline has logical-error rate {c['majority_baseline_test_logical_error_rate']:.4f} "
             f"(test positive rate {c['test_positive_rate']:.4f}); the supplied decoders have {decoders}.", '',
             f"The MLP is at chance level: its balanced accuracy is {m['balanced_accuracy']:.4f} and its Brier score "
             f"({m['brier_score']:.4f}) is worse than the 0.25 of a constant 0.5 forecast, so its probabilities are "
             f"over-confident. Training stopped at {settings['iterations']} iterations"
             + (' without converging (warning in `run.json`)' if settings['warnings'] else '')
             + '. This is a negative result for this bounded setup, reported as observed. It confirms that the '
             'bits are unpacked in the documented order and that the pipeline runs end to end; it says nothing '
             'about what a larger or structured model could learn.', '',
             'What the flat 200-bit vector does not show explicitly:', '',
             '- **Position.** Index *i* stands for a detector at some qubit location, but the coordinates are not '
             'in the ML table, so two bits from neighbouring stabilizers look as unrelated as two distant ones.',
             '- **Neighbourhood.** Errors appear as pairs or chains of nearby fired detectors. The model sees no '
             'adjacency and has to learn every local pattern separately at every position.',
             '- **Time.** The bits come from 25 rounds of 8 stabilizers, but the vector does not mark which bits '
             'are the same stabilizer in successive rounds, so a pattern that repeats in time must be relearned '
             'for each round.',
             '- **Context.** The processor location of each experiment and the boundary that defines the logical '
             'observable are not inputs, although they decide which detector chains flip the outcome.',
             '', f"With {record['split_rows']['task_c']['train']:,} training shots and 200 inputs, a small MLP "
             'without this structure has little chance to recover it, which is consistent with the chance-level result. Task C uses a smaller test subset '
             'than Task B, so its numbers are only compared with the reference values above.']
    return lines


def _discarded_and_limits(record):
    return ['', '## Information discarded by the representations', '',
            '- **Task A:** the physical fault rate (it defines the split, and the label rate rises with it), '
            'and the round and check identity beyond position in the vector. Identical syndromes occur with both '
            'labels, so the input cannot separate those observations.',
            '- **Task B:** the raw detector pattern is reduced to one density value, and each decoder to a single '
            'bit with no confidence. Experiment and processor location are dropped. Measurements and sweep bits '
            'are not in the ML table.',
            '- **Task C:** detector geometry, round structure and experiment identity (see above), and all shots '
            'outside the prescribed bounded subset.',
            '', '## Limitations', '',
            '- One fixed split, seed and setting per model; no confidence intervals or repeated runs, so small '
            'differences (for example between the combined model and the best supplied decoder) are not '
            'established as real.',
            '- A fixed 0.5 threshold. Validation data could have been used to choose it but was not, so the '
            'logical-error rates reflect the uncalibrated default, which matters most for the imbalanced Task A.',
            '- Task A is simulated data at distance three; its result does not transfer to hardware without '
            'evidence. Task B and C results describe these five experiments only.',
            '- QASMBench has no labeled shots and is not used in Part II.',
            '', '## Traceability and saved files', '',
            'Every row in `predictions.parquet` keeps the `example_id` of its ML row (columns `example_id`, '
            '`model_id`, `label`, `prediction`, nullable `probability`, `split`; validation and test rows are '
            'saved, labelled by `split`). Part I resolves each `example_id` to Gold through the views '
            '`gold.ml_syndrome_source` and `gold.ml_google_source`, then to Silver and Bronze through '
            '`results/part1/source_trace.parquet`. `python -m quantum_lake_student.cli trace` attaches the saved '
            'test predictions to the two examples in `results/part1/trace_examples.json`.', '',
            'Files: `models/` (fitted logistic regressions, MLP and prior files), `predictions.parquet`, '
            '`metrics.json` (all metrics and timings by task, model, distance and split), `run.json` '
            '(provenance, feature order, split rules, settings, warnings and the context figures quoted here).']


def write_report(output: Path) -> None:
    metrics = json.loads((output / 'metrics.json').read_text())
    record = json.loads((output / 'run.json').read_text())
    lines = [*_intro(record), *_inputs_section(record), *_choices_section(record)]
    if 'task_a' in metrics:
        lines += _task_a(metrics, record)
    if all(t in metrics for t in ('task_b_d3', 'task_b_d5')) and 'task_b_d3' in record.get('report_context', {}):
        lines += _task_b(metrics, record)
    if 'task_c' in metrics and 'task_c' in record.get('report_context', {}):
        lines += _task_c(metrics, record)
    lines += _discarded_and_limits(record)
    (output / 'report.md').write_text('\n'.join(lines) + '\n')
